Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'x'
    - 'y'

Naming/PredicateName:
  AllowedMethods:
    - has_center?
    - has_no_consecutive_center?
    - has_no_intermediate_center?
    - has_same_center_at_extremes?
    - has_unique_cities?
    - has_unique_places?
    - is_a?

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Documentation:
  Enabled: false

# Experimental cops
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
