require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/MethodParameterName:
  AllowedNames:
    - 'x'
    - 'y'

Naming/PredicateName:
  AllowedMethods:
    - has_center?
    - has_no_consecutive_center?
    - has_no_intermediate_center?
    - has_same_center_at_extremes?
    - has_unique_cities?
    - has_unique_places?
    - is_a?

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Style/Copyright:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/ExampleLength:
  Max: 10
